---
title: "Curso R" 
---

#Acerca de este curso

Este curso te proporcionará las bases del lenguaje de programación estadística R, uno de los lenguajes de programación más utilizados para la estadística, el cual te permitirá escribir programas que lean, manipulen y analicen datos cuantitativos. Te explicaremos la instalación del lenguaje, fundamentos de programación y también verás una introducción a los sistemas base de gráficos. Los últimos módulos están orientados a la construcción 
de documentos rmarkdown y de aplicaciones web a través del paquete shiny. Además también abordarás la utilización de uno de los IDEs más populares entre la comunidad de usuarios de R, llamado RStudio.

### Dr. Ing. Ignacio Cassol

El Dr. Cassol es ingeniero en informática, Master en Software engineering por el Instituto de Buenos Aires (ITBA) y por el Politénico de Madrid. Es doctor en Matemática computacional e industrial (UNICEN) y realizó una estancia post-doctoral como investigador y profesor visitante en TECNUN (Escuela de Ingenieros de la Universidad de Navarra). Además de su tarea docente, es Director de Ingeniería Biomédicas de la Facultad de Ingeniería de la Universidad Austral. Sus areas de investigación son le refactorización de código estructurado y la genómica y la ciencia de datos.

* icassol@austral.edu.ar

### Bautista Baiocchi-lora

Bautista Baiocchi-lora es un estudiante autodidacta de la informática. Comenzo a los trece años, hábil en una variedad de lenguajes, especializándose en las áreas de Reverse Engineering, la ciencia de datos, y Full Stack Development. Actualmente se encuentra como desarrollador Full Stack y estudiante de Ingeniería Informática en la Universidad Austral.

* bautista.baiocchi@ing.austral.edu.ar
* [Github](https://github.com/Bautista-Baiocchi-lora)
* [Linkedin](https://www.linkedin.com/in/bautista-baiocchi-lora/)
